trajectory_controller:
  trajectory_controller:
    ros__parameters:
      controller_period_ms: 100
      landed_altitude_threshold: 0.5
      reached_position_euclidean_distance_threshold: 0.1
      min_target_altitude: 1.
      position_MPC_dt: 0.1
      position_MPC_vx_max: 2.
      position_MPC_vy_max: 2.
      position_MPC_vz_max: 2.
      position_MPC_vpsi_max: 1.56
      position_MPC_ax_max: 1.0
      position_MPC_ay_max: 1.0
      position_MPC_az_max: 1.0
      position_MPC_apsi_max: 1.56
      position_MPC_wx: 1.
      position_MPC_wy: 1.
      position_MPC_wz: 1.
      position_MPC_wpsi: 1.
      position_MPC_wvx: 1.0
      position_MPC_wvy: 1.0
      position_MPC_wvz: 1.0
      position_MPC_wvpsi: 1.
      position_MPC_wax: 0.01
      position_MPC_way: 0.01
      position_MPC_waz: 0.01
      position_MPC_wapsi: 0.
      position_MPC_wjx: 0.1
      position_MPC_wjy: 0.1
      position_MPC_wjz: 0.1
      position_MPC_wx_last: 10.
      position_MPC_wy_last: 10.
      position_MPC_wz_last: 10.
      position_MPC_wpsi_last: 1.
      position_MPC_wvx_last: 1.
      position_MPC_wvy_last: 1.
      position_MPC_wvz_last: 1.
      position_MPC_wvpsi_last: 2.
      position_MPC_wax_last: 0.1
      position_MPC_way_last: 0.1
      position_MPC_waz_last: 0.1
      position_MPC_wapsi_last: 0.
      cable_landing_MPC_dt: 0.1
      cable_landing_MPC_vx_max: 10.
      cable_landing_MPC_vy_max: 10.
      cable_landing_MPC_vz_max: 5.
      cable_landing_MPC_vpsi_max: 1.06
      cable_landing_MPC_ax_max: 10.
      cable_landing_MPC_ay_max: 10.
      cable_landing_MPC_az_max: 10.
      cable_landing_MPC_apsi_max: 1.06
      cable_landing_MPC_wx: 0.
      cable_landing_MPC_wy: 0.
      cable_landing_MPC_wz: 0.
      cable_landing_MPC_wpsi: 0.
      cable_landing_MPC_wvx: 0.
      cable_landing_MPC_wvy: 0.
      cable_landing_MPC_wvz: 0.
      cable_landing_MPC_wvpsi: 0.
      cable_landing_MPC_wx_last: 10.
      cable_landing_MPC_wy_last: 10.
      cable_landing_MPC_wz_last: 1.
      cable_landing_MPC_wpsi_last: 10.
      cable_landing_MPC_wvx_last: 5.
      cable_landing_MPC_wvy_last: 5.
      cable_landing_MPC_wvz_last: 5.
      cable_landing_MPC_wvpsi_last: 5.

cable_drum_controller:
  cable_drum_controller:
    cable_drum_initial_gain: 15
    cable_drum_initial_reference: 8